name: Build CMake Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 新增手动触发选项

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpcap-dev \
          libssl-dev \
          libpcre2-dev \
          libxml2-dev \
          liblua5.X-0 \
          libbson-dev \
          libmongoc-dev

    - name: Build project
      run: |
        chmod +x ./build.sh
        ./build.sh 
